"""add post reletionship

Revision ID: 91b3c38320ef
Revises: d22d78e29a2c
Create Date: 2019-04-30 15:47:44.768473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b3c38320ef'
down_revision = 'd22d78e29a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('user', 'image_file')
    # ### end Alembic commands ###
